name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode environment
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build the project
      working-directory: TouchPad/tap&sendForMac/tap&sendForMac.xcodeproj/project.pbxproj  # Replace with the actual path to your .xcodeproj or .xcworkspace
      run: |
        xcodebuild -scheme tap_sendForMac -sdk macosx -destination 'platform=macOS,arch=x86_64' clean build

    - name: Archive the build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: TouchPad/tap&sendForMac/tap&sendForMac.xcodeproj/project.pbxproj/build/Release/tap_sendForMac.app  # Adjust the path if necessary

    - name: Clean up build
      run: |
        rm -rf TouchPad/tap&sendForMac/tap&sendForMac.xcodeproj/project.pbxproj/build/