name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode environment
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Install dependencies
      run: |
        # Install CocoaPods if you are using it
        if [ -f Podfile ]; then
          sudo gem install cocoapods
          pod install
        fi

    - name: Build the project
      run: |
        xcodebuild -scheme TapAndSendForMac -sdk macosx -destination 'platform=macOS,arch=x86_64' clean build

    - name: Archive the build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: build/Release/TapAndSendForMac.app

    - name: Clean up build
      run: |
        rm -rf build/